files:
  - source: /mathmaps/en/**/*.json
    translation: /mathmaps/%two_letters_code%/**/%original_file_name%
  - source: /mathmaps/en/**/*.yaml
    translation: /mathmaps/%two_letters_code%/**/%original_file_name%
